language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements_nornir1.txt

# command to run tests
script:
  - pylama .
  - black --check .
  - cd tests
  - py.test -s -v test_class1.py
  - py.test -s -v test_class2.py::test_class2_ex1a
  - py.test -s -v test_class2.py::test_class2_ex1b
  - py.test -s -v test_class2.py::test_class2_ex1c
  - py.test -s -v test_class2.py::test_class2_ex1d
